<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Saldo_akhir_model extends CI_Model
{

    public $table = 'tbl_saldo_akhir';
    public $id = 'sak_id';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('sak_id', $q);
	$this->db->or_like('sak_id', $q);
	$this->db->or_like('sak_jumlah', $q);
	$this->db->or_like('sak_id_bulan', $q);
	$this->db->or_like('sak_id_tahun', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('sak_id', $q);
	$this->db->or_like('sak_id', $q);
	$this->db->or_like('sak_jumlah', $q);
	$this->db->or_like('sak_id_bulan', $q);
	$this->db->or_like('sak_id_tahun', $q);
    $this->db->join('tbl_bulan', 'sak_id_bulan=bulan_id','left');
    $this->db->join('tbl_tahun', 'sak_id_tahun=tahun_id','left');
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete data by thn
    function delete_bytahun($id)
    {
        $this->db->where('sak_id_tahun', $id);
        $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk(){
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data); 
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }
//check pk data is exists 

        function is_exist($id){
         $query = $this->db->get_where($this->table, array($this->id => $id));
         $count = $query->num_rows();
         if($count > 0){
            return true;
         }else{
            return false;
         }
        }


}

/* End of file Saldo_akhir_model.php */
/* Location: ./application/models/Saldo_akhir_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-13 17:45:55 */
/* http://harviacode.com */